const actions = {
    CONTINENTS_FETCHED: 'CONTINENTS_FETCHED',
    CONTINENT_SELECT: 'CONTINENT_SELECT',
    REGIONS_FETCHED: 'REGIONS_FETCHED',
    REGION_SELECT: 'REGION_SELECT',
    COUNTRIES_FETCHED: 'COUNTRIES_FETCHED',
    COUNTRY_SELECT: 'COUNTRY_SELECTED',
    CITIES_FETCHED: 'CITIES_FETCHED',
    LANGUAGES_FETCHED: 'LANGUAGES_FETCHED',
    SHOW_LANGUAGES: 'SHOW_LANGUAGES',
    SHOW_CITIES: 'SHOW_CITIES',
    SHOW_COUNTRY_SUMMARY: 'SHOW_COUNTRY_SUMMARY',
    CREATE_NEW_CITY: 'CREATE_NEW_CITY',
    EDIT_CITY: 'EDIT_CITY',
    DELETE_CITY: 'DELETE_CITY',
    EDIT_CITY_PROP: 'EDIT_CITY_PROP',
    CANCEL_CITY_EDIT: 'CANCEL_CITY_EDIT',
    SAVE_CITY: 'SAVE_CITY',
    CITY_SAVED: 'CITY_SAVED',
    CITY_DELETED: 'CITY_DELETED',
    CITY_CREATED: 'CITY_CREATED',
    CITY_NEXT_PAGE: 'CITY_NEXT_PAGE',
    CITY_PREV_PAGE: 'CITY_PREV_PAGE'
}

export default actions;