const actions = {
    CONTINENTS_FETCHED: 'CONTINENTS_FETCHED',
    CONTINENT_SELECT: 'CONTINENT_SELECT',
    REGIONS_FETCHED: 'REGIONS_FETCHED',
    REGION_SELECT: 'REGION_SELECT',
    COUNTRIES_FETCHED: 'COUNTRIES_FETCHED',
    COUNTRY_SELECT: 'COUNTRY_SELECTED',
    CITIES_FETCHED: 'CITIES_FETCHED',
    LANGUAGES_FETCHED: 'LANGUAGES_FETCHED',
    SHOW_LANGUAGES: 'SHOW_LANGUAGES',
    SHOW_CITIES: 'SHOW_CITIES',
    SHOW_COUNTRY_SUMMARY: 'SHOW_COUNTRY_SUMMARY',
}

export default actions;